import AnimatedText from '@/components/AnimatedText'
import Layout from '@/components/Layout'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import React, { useRef } from 'react'
import project1 from '../../public/images/projects/crypto-screener-cover-image.jpg'
import { motion, useMotionValue } from 'framer-motion'

const FramerImage = motion(Image)

const MovingImage = ({img, title, link}) => {
    const x = useMotionValue(0)
    const y = useMotionValue(0)
    const imgRef = useRef(null)
    function handelMouse(event){
        imgRef.current.style.display = 'inline-block';
        x.set(event.pageX)
        y.set(-5)
    }
    function handelMouseLeave(event){
        imgRef.current.style.display = 'none';
        x.set(0)
        y.set(0)
    }
    return (
        <Link href={link}
            onMouseMove={handelMouse}
            onMouseLeave={handelMouseLeave}
        >
            <h2 className="capitalize text-xl font-semibold hover:underline">{title}</h2>
            <FramerImage 
            style={{x: x, y: y}}
            initial={{opacity:0}}
            whileInView={{opacity:1, transition:{duration:0.5}}}
            ref={imgRef} src={img} alt={title} className="z-10 w-96 h-auto hidden absolute rounded-lg md:!hidden"/>
        </Link>
    )
}

const Article = ({img, title, date, link}) => {
    return (
        <motion.li 
            initial={{y:200}}
            whileInView={{y: 0, transition:{duration:0.5}}}
            
        className="w-full relative p-4 py-6 my-4 rounded-xl flex items-center justify-between bg-light text-dark first:mt-0 border border-solid border-dark border-r-4 border-b-4 dark:bg-dark dark:text-light dark:border-light">
            <MovingImage
                title={title}
                link={link}
                img={img}
            />
            <span className="text-primary font-semibold pl-4 dark:text-primaryDark">{date}</span>
        </motion.li>
    )
}

const FeaturedArticle = ({title, img, link, summary, time}) => {
    return (
        <li className='col-span-1 w-full rounded-2xl border border-solid border-dark bg-light shadow-2xl p-6 relative dark:bg-dark dark:border-light'>
            <div className='absolute top-0 -right-3 -z-10 w-[102%] h-[103%] rounded-[2rem] bg-dark dark:bg-light' />
            
            <Link href={link} target="_blank" className="w-full cursor-pointer overflow-hidden rounded-lg my-4">
                <Image src={img} alt={title} className="w-full h-auto" 
                    priority
                    sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw"
                />
            </Link>

            <Link href={link} target="_blank" className='hover:underline underline-offset-2 dark:text-light'>
                    <h2 className='capitalize my-2 w-full text-2xl font-bold xs:text-lg'>{title}</h2>
                </Link>
                <p className="dark:text-light">{summary}</p>
                <div className="dark:text-primaryDark">{time}</div>

        </li>
    )
}
export default function articles() {
  return (
    <>
        <Head>
            <title>SandDigital | Articles Page</title>
            <meta name="description" content="Generated by create next app" />
        </Head>
        <main className="flex w-full mb-16 flex-col items-center justify-center">
            <Layout className='pt-16'>
                <AnimatedText text="Words Can Change The World!" className="mb-16 lg:!text-7xl sm:!text-6xl xs:!text-4xl sm:mb-8" />
                <ul className='grid grid-cols-2 gap-16 lg:gap-8 md:grid-cols-1 md:gap-y-16'>
                    <FeaturedArticle
                        title="Build A Custom Pagination Component In Reactjs From Scratch"
                        summary="Learn how to build a custom pagination component in ReactJS from scratch.  Follow this step-by-step guide to integrate Pagination component in your ReactJS project."
                        link="/"
                        time="9 Mins."
                        img={project1}
                    />
                    <FeaturedArticle
                        title="Build A Custom Pagination Component In Reactjs From Scratch"
                        summary="Learn how to build a custom pagination component in ReactJS from scratch.  Follow this step-by-step guide to integrate Pagination component in your ReactJS project."
                        link="/"
                        time="9 Mins."
                        img={project1}
                    />
                </ul>
                <h2 className='mt-32 w-full text-4xl text-center my-16 font-bold dark:text-light'>All Articles</h2>
                <ul>
                    <Article
                        title="Form Validation In Reactjs: Build A Reusable Custom Hook For Inputs And Error Handling"
                        date="March 2023"
                        link="/"
                        img={project1}
                    />
                    <Article
                        title="Form Validation In Reactjs: Build A Reusable Custom Hook For Inputs And Error Handling"
                        date="March 2023"
                        link="/"
                        img={project1}
                    />
                    <Article
                        title="Form Validation In Reactjs: Build A Reusable Custom Hook For Inputs And Error Handling"
                        date="March 2023"
                        link="/"
                        img={project1}
                    />
                    <Article
                        title="Form Validation In Reactjs: Build A Reusable Custom Hook For Inputs And Error Handling"
                        date="March 2023"
                        link="/"
                        img={project1}
                    />
                    <Article
                        title="Form Validation In Reactjs: Build A Reusable Custom Hook For Inputs And Error Handling"
                        date="March 2023"
                        link="/"
                        img={project1}
                    />
                    <Article
                        title="Form Validation In Reactjs: Build A Reusable Custom Hook For Inputs And Error Handling"
                        date="March 2023"
                        link="/"
                        img={project1}
                    />
                    <Article
                        title="Form Validation In Reactjs: Build A Reusable Custom Hook For Inputs And Error Handling"
                        date="March 2023"
                        link="/"
                        img={project1}
                    />
                </ul>
            </Layout>
        </main>
    </>
  )
}
