import React, { useEffect, useState } from 'react'
import Layout from '@/components/Layout'
import Head from 'next/head'
import AnimatedText from '@/components/AnimatedText'
import Link from 'next/link'
import Image from 'next/image'
import { GithubIcon } from '@/components/Icons'
import project1 from '../../public/images/projects/crypto-screener-cover-image.jpg'

const FeaturedProject = ({type, title, summary, img, link, github}) => {
    return (
        <article className='w-full flex items-center justify-between rounded-br-2xl rounded-3xl border border-solid border-dark bg-light shadow-2xl p-12 relative dark:bg-dark dark:border-light lg:flex-col lg:p-8 xs:rounded-2xl xs:rounded-br-3xl xs:p-4'>
            <div className='absolute top-0 -right-3 -z-10 w-[101%] h-[103%] rounded-[2.5rem] bg-dark rounded-br-3xl dark:bg-light xs:-right-2 xs:h-[102%] xs:w-full xs:rounded-[1.5rem]' />
            <Link href={link} target="_blank" className="w-1/2 cursor-pointer overflow-hidden rounded-lg lg:w-full">
                <Image 
                src={img} 
                alt={title} 
                className="w-full h-auto" 
                priority
                sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw"
                />
            </Link>
            <div className="w-1/2 flex flex-col items-start justify-between pl-6 dark:text-light lg:w-full lg:pl-0 lg:mt-4">
                <span className='text-primary font-medium text-xl dark:text-primaryDark'>{type}</span>
                <Link href={link} target="_blank" className='hover:underline underline-offset-2'>
                    <h2 className='my-2 w-full text-left text-4xl font-bold'>{title}</h2>
                </Link>
                <p className='my-2 font-t-medium text-dark dark:text-light'>{summary}</p>
                <div className="mt-2 flex items-center">
                    <Link href={github} terget="_blank" className="w-10"><GithubIcon /></Link>
                    <Link href={link} terget="_blank" className='ml-4 rounded-lg bg-dark text-light p-2 text-lg px-6 font-semibold dark:bg-light dark:text-dark'>Visit Project</Link>
                </div>
            </div>

        </article>
    )
}
const Project = ({type, title, img, link, github}) => {
    return (
        <article className='w-full flex flex-col items-center justify-center rounded-2xl border border-solid border-dark bg-light shadow-2xl p-6 relative dark:bg-dark dark:border-light dark:text-light lg:flex-col lg:p-8 xs:rounded-2xl xs:rounded-br-3xl xs:p-4'>
            <div className='absolute top-0 -right-3 -z-10 w-[102%] h-[103%] rounded-[2rem] bg-dark dark:bg-light ' />
            <Link href={link} target="_blank" className="w-full cursor-pointer overflow-hidden rounded-lg">
                <Image 
                    src={img} 
                    alt={title} 
                    className="w-full h-auto" 
                    priority
                    sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw"
                />
            </Link>
            <div className="w-full flex flex-col items-start justify-between mt-4">
                <span className='text-primary font-medium text-xl dark:text-primaryDark'>{type}</span>
                <Link href={link} target="_blank" className='hover:underline underline-offset-2'>
                    <h2 className='my-2 w-full text-left text-4xl font-bold dark:text-light'>{title}</h2>
                </Link>
                
                <div className="w-full mt-2 flex items-center justify-between">
                    <Link href={link} terget="_blank" className='text-lg font-semibold underline dark:text-light'>Visit</Link>
                    <Link href={github} terget="_blank" className="w-10"><GithubIcon /></Link>
                </div>
            </div>

        </article>
    )
}

export default function Projects() {
    const [count, setCount] = useState(0);
   
  return (
    <>
        <Head>
            <title>SandDigital | Projects Page</title>
            <meta name="description" content="Generated by create next app" />
        </Head>
        <main className="flex w-full mb-16 flex-col items-center justify-center">
            <Layout className='pt-16'>
                <AnimatedText text="Imagination Trumps Knowledge!" 
                className="mb-16 lg:!text-7xl sm:!text-6xl xs:!text-4xl sm:mb-8" />

                <div className="grid grid-clos-12 gap-24 gap-y-32 xl:gap-x-16 lg:gap-x-8 md:gap-y-24 sm:gap-x-0">
                    <div className="col-span-12">
                        <FeaturedProject
                            title="Crypto Screener Application"
                            summary="A feature-rich Crypto Screener App using React, Tailwind CSS, Context API, React Router and Recharts. 
                            It shows detail regarding almost all the cryptocurrency. You can easily convert the price in your 
                            local currency."
                            link="/"
                            type="Featured Project"
                            img={project1}
                            github="https://github.com/"
                        />
                    </div>
                    <div className="col-span-6 sm:col-span-12">
                        <Project
                            title="Crypto Screener Application"
                            link="/"
                            type="Project 1"
                            img={project1}
                            github="https://github.com/"
                        />
                    </div>
                    <div className="col-span-6 sm:col-span-12">
                        <Project
                            title="Crypto Screener Application"
                            link="/"
                            type="Project 2"
                            img={project1}
                            github="https://github.com/"
                        />
                    </div>
                    <div className="col-span-12">
                        <FeaturedProject
                            title="Crypto Screener Application"
                            summary="A feature-rich Crypto Screener App using React, Tailwind CSS, Context API, React Router and Recharts. 
                            It shows detail regarding almost all the cryptocurrency. You can easily convert the price in your 
                            local currency."
                            link="/"
                            type="Featured Project 2"
                            img={project1}
                            github="https://github.com/"
                        />
                    </div>
                    <div className="col-span-6 sm:col-span-12">
                        <Project
                            title="Crypto Screener Application"
                            link="/"
                            type="Project 3"
                            img={project1}
                            github="https://github.com/"
                        />
                    </div>
                    <div className="col-span-6 sm:col-span-12">
                        <Project
                            title="Crypto Screener Application"
                            link="/"
                            type="Project 4"
                            img={project1}
                            github="https://github.com/"
                        />
                    </div>
                </div>
                
                
            </Layout>
        </main>
    </>
  )
}
